class ACIError(Exception):
    """Base class for user-facing errors."""

class EmptyQueryError(ACIError): ...
class RepositoryNotFoundError(ACIError): ...
class InvalidCommitError(ACIError): ...
class IndexNotFoundError(ACIError): ...
class UnsupportedLanguageError(ACIError): ...
class ModelLoadError(ACIError): ...
class MissingEmbeddingsError(ACIError): ...
